"""edit table product img

Revision ID: 6f0ac81d301d
Revises: b3a8a7a45edc
Create Date: 2024-12-16 20:50:27.002254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f0ac81d301d'
down_revision = 'b3a8a7a45edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_imgs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('img_url', sa.Unicode(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_imgs', schema=None) as batch_op:
        batch_op.drop_column('img_url')
        batch_op.drop_column('mime_type')

    # ### end Alembic commands ###
