"""upgrade table

Revision ID: b3a8a7a45edc
Revises: c17cae3fe42a
Create Date: 2024-12-16 20:22:06.857706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a8a7a45edc'
down_revision = 'c17cae3fe42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar_imgs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mime_type', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('img_url', sa.Unicode(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('avatar_imgs', schema=None) as batch_op:
        batch_op.drop_column('img_url')
        batch_op.drop_column('mime_type')

    # ### end Alembic commands ###
